name: "P2P book distribution"
description: "Buy multiple copies of books at half price, and keep them for others to buy from you."

url: http://localhost:4000
baseurl: /p2p-book-distribution
liveurl: http://p2p.electricbookworks.com
markdown: kramdown
permalink: pretty
highlighter: rouge

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      image: "p2p-book-distribution.png"
      layout: "default"
